### ISSUE TITLE
pract 4 y5.

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/practica-4y5-proo#1]
[pract 4y 5.contractos inteligentes.pdf](https://github.com/SistemasTecTlaxiaco/practica-4y5-proo/files/8683186/pract.4y.5.contractos.inteligentes.pdf)

**Comment by IsaHuerta23** [comment]
Portada: 25 puntos.
Procedimiento: 25 puntos.
Figuras, ilustraciones y fotografías: 25 puntos. 
Resultados y conclusiones: 25 puntos.
Total: 100 puntos = Calificación: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
